/* Generated by bindings/c/tools/generate_fixtures.py. */
#ifndef COGGATE_GENERATED_FIXTURES_H
#define COGGATE_GENERATED_FIXTURES_H

#include <stddef.h>
#include <stdint.h>

typedef struct ag_binding_fixture_case {
    const char *id;
    const char *operation;
    const char *submission_json;
    const char *binding_hex;
    const char *lifecycle_json;
    const char *keys_json;
    int32_t expected_status;
    const char *expected_code;
    const char *expected_outcome_json;
    const char *expected_trace_json;
    uint32_t expected_release_count;
    const char *forbidden_sentinels_json;
} ag_binding_fixture_case;

typedef struct ag_binding_fixture_vectors {
    const char *challenge_id;
    const char *nonce;
    const char *answer;
    const char *wrong_answer;
    const uint8_t *binding;
    size_t binding_len;
    const uint8_t *token;
    size_t token_len;
    const char *active_key_id;
    const uint8_t *active_key;
    size_t active_key_len;
    const char *old_key_id;
    const uint8_t *old_key;
    size_t old_key_len;
    const char *private_material_json;
    const char *observer_allowlist_json;
} ag_binding_fixture_vectors;

static const uint8_t AG_BINDING_FIXTURE_BINDING[] = {0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77};
static const uint8_t AG_BINDING_FIXTURE_TOKEN[] = {0xaa, 0xbb, 0xcc, 0xdd};
static const uint8_t AG_BINDING_FIXTURE_ACTIVE_KEY[] = {0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11};
static const uint8_t AG_BINDING_FIXTURE_OLD_KEY[] = {0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66};

static const ag_binding_fixture_vectors AG_BINDING_FIXTURE_VECTORS = {
    "Y2hhbGxlbmdlLTEyMzQ1Ng",
    "bm9uY2UtMTIzNDU2Nzg5MA",
    "YQ",
    "Yg",
    AG_BINDING_FIXTURE_BINDING,
    sizeof(AG_BINDING_FIXTURE_BINDING),
    AG_BINDING_FIXTURE_TOKEN,
    sizeof(AG_BINDING_FIXTURE_TOKEN),
    "active-2026-09",
    AG_BINDING_FIXTURE_ACTIVE_KEY,
    sizeof(AG_BINDING_FIXTURE_ACTIVE_KEY),
    "2026-08",
    AG_BINDING_FIXTURE_OLD_KEY,
    sizeof(AG_BINDING_FIXTURE_OLD_KEY),
    "{\"answer_encoding\":\"base64url\",\"answer_mac\":\"ccdffbb67b4c9da34f91d56d12970b311d7345e8bcf579d1326fc4a78633330c\",\"challenge_id\":\"Y2hhbGxlbmdlLTEyMzQ1Ng\",\"expires_at\":1788062408,\"generator_version\":\"1.0\",\"issued_at\":1788062400,\"mac_key_id\":\"2026-08\",\"nonce\":\"bm9uY2UtMTIzNDU2Nzg5MA\"}",
    "[\"event\",\"challenge_id\",\"generator_version\",\"disposition\",\"elapsed_since_issue_us\",\"duration_us\"]",
};

static const ag_binding_fixture_case AG_BINDING_FIXTURE_CASES[] = {
    {
        "accepted",
        "verify",
        "{\"answer\":\"YQ\",\"challenge_id\":\"Y2hhbGxlbmdlLTEyMzQ1Ng\",\"nonce\":\"bm9uY2UtMTIzNDU2Nzg5MA\"}",
        "0011223344556677",
        "{\"begin_status\":\"ok\",\"callback_exception\":false,\"finish_status\":\"ok\",\"material\":\"primary\",\"replay\":false,\"token\":\"default\"}",
        "{\"callback_exception\":false,\"key_id\":\"old\",\"status\":\"ok\"}",
        INT32_C(0),
        "ok",
        "{\"status\":\"accepted\"}",
        "[\"begin_attempt\",\"release:token\",\"release:material\",\"key_by_id:old\",\"release:key\",\"finish_attempt:accepted\",\"observe:verification_completed\"]",
        UINT32_C(3),
        "[\"PRIVATE_ANSWER_SENTINEL\",\"KEY_SENTINEL\"]"
    },
    {
        "answer_mismatch",
        "verify",
        "{\"answer\":\"Yg\",\"challenge_id\":\"Y2hhbGxlbmdlLTEyMzQ1Ng\",\"nonce\":\"bm9uY2UtMTIzNDU2Nzg5MA\"}",
        "0011223344556677",
        "{\"begin_status\":\"ok\",\"callback_exception\":false,\"finish_status\":\"ok\",\"material\":\"primary\",\"replay\":false,\"token\":\"default\"}",
        "{\"callback_exception\":false,\"key_id\":\"old\",\"status\":\"ok\"}",
        INT32_C(5),
        "answer_mismatch",
        NULL,
        "[\"begin_attempt\",\"release:token\",\"release:material\",\"key_by_id:old\",\"release:key\",\"finish_attempt:rejected\",\"observe:verification_completed\"]",
        UINT32_C(3),
        "[\"PRIVATE_ANSWER_SENTINEL\",\"KEY_SENTINEL\"]"
    },
    {
        "callback_exception",
        "verify",
        "{\"answer\":\"YQ\",\"challenge_id\":\"Y2hhbGxlbmdlLTEyMzQ1Ng\",\"nonce\":\"bm9uY2UtMTIzNDU2Nzg5MA\"}",
        "0011223344556677",
        "{\"begin_status\":\"exception\",\"callback_exception\":true,\"finish_status\":\"unused\",\"material\":\"none\",\"replay\":false,\"token\":\"none\"}",
        "{\"callback_exception\":false,\"key_id\":\"none\",\"status\":\"unused\"}",
        INT32_C(7),
        "internal_error",
        NULL,
        "[\"begin_attempt:exception\",\"observe:service_failed\"]",
        UINT32_C(0),
        "[\"CALLBACK_EXCEPTION_SENTINEL\"]"
    },
    {
        "close_after_use",
        "close",
        NULL,
        "",
        "{\"begin_status\":\"unused\",\"callback_exception\":false,\"finish_status\":\"unused\",\"material\":\"none\",\"replay\":false,\"token\":\"none\"}",
        "{\"callback_exception\":false,\"key_id\":\"none\",\"status\":\"unused\"}",
        INT32_C(0),
        "ok",
        NULL,
        "[\"service_destroy\"]",
        UINT32_C(0),
        "[\"CLOSED_SERVICE_SENTINEL\"]"
    },
    {
        "exact_release",
        "release",
        "{\"answer\":\"YQ\",\"challenge_id\":\"Y2hhbGxlbmdlLTEyMzQ1Ng\",\"nonce\":\"bm9uY2UtMTIzNDU2Nzg5MA\"}",
        "0011223344556677",
        "{\"begin_status\":\"ok\",\"callback_exception\":false,\"finish_status\":\"ok\",\"material\":\"primary\",\"replay\":false,\"token\":\"default\"}",
        "{\"callback_exception\":false,\"key_id\":\"old\",\"status\":\"ok\"}",
        INT32_C(0),
        "ok",
        "{\"status\":\"accepted\"}",
        "[\"begin_attempt\",\"release:token\",\"release:material\",\"key_by_id:old\",\"release:key\",\"finish_attempt:accepted\"]",
        UINT32_C(3),
        "[\"DOUBLE_RELEASE_SENTINEL\"]"
    },
    {
        "finish_failure",
        "verify",
        "{\"answer\":\"YQ\",\"challenge_id\":\"Y2hhbGxlbmdlLTEyMzQ1Ng\",\"nonce\":\"bm9uY2UtMTIzNDU2Nzg5MA\"}",
        "0011223344556677",
        "{\"begin_status\":\"ok\",\"callback_exception\":false,\"finish_status\":\"internal\",\"material\":\"primary\",\"replay\":false,\"token\":\"default\"}",
        "{\"callback_exception\":false,\"key_id\":\"old\",\"status\":\"ok\"}",
        INT32_C(7),
        "internal_error",
        NULL,
        "[\"begin_attempt\",\"release:token\",\"release:material\",\"key_by_id:old\",\"release:key\",\"finish_attempt:accepted\",\"observe:service_failed\"]",
        UINT32_C(3),
        "[\"FINISH_FAILURE_SENTINEL\"]"
    },
    {
        "key_rotation_old_key",
        "verify",
        "{\"answer\":\"YQ\",\"challenge_id\":\"Y2hhbGxlbmdlLTEyMzQ1Ng\",\"nonce\":\"bm9uY2UtMTIzNDU2Nzg5MA\"}",
        "0011223344556677",
        "{\"begin_status\":\"ok\",\"callback_exception\":false,\"finish_status\":\"ok\",\"material\":\"primary\",\"replay\":false,\"token\":\"default\"}",
        "{\"callback_exception\":false,\"key_id\":\"old\",\"status\":\"ok\"}",
        INT32_C(0),
        "ok",
        "{\"status\":\"accepted\"}",
        "[\"begin_attempt\",\"release:token\",\"release:material\",\"key_by_id:old\",\"release:key\",\"finish_attempt:accepted\",\"observe:verification_completed\"]",
        UINT32_C(3),
        "[\"ACTIVE_KEY_SENTINEL\"]"
    },
    {
        "lifecycle_already_consumed",
        "verify",
        "{\"answer\":\"YQ\",\"challenge_id\":\"Y2hhbGxlbmdlLTEyMzQ1Ng\",\"nonce\":\"bm9uY2UtMTIzNDU2Nzg5MA\"}",
        "0011223344556677",
        "{\"begin_status\":\"already_consumed\",\"callback_exception\":false,\"finish_status\":\"unused\",\"material\":\"none\",\"replay\":false,\"token\":\"none\"}",
        "{\"callback_exception\":false,\"key_id\":\"none\",\"status\":\"unused\"}",
        INT32_C(0),
        "ok",
        "{\"status\":\"rejected\",\"reason\":\"already_consumed\"}",
        "[\"begin_attempt\",\"observe:verification_completed\"]",
        UINT32_C(0),
        "[\"MATERIAL_SENTINEL\"]"
    },
    {
        "lifecycle_attempts_exhausted",
        "verify",
        "{\"answer\":\"YQ\",\"challenge_id\":\"Y2hhbGxlbmdlLTEyMzQ1Ng\",\"nonce\":\"bm9uY2UtMTIzNDU2Nzg5MA\"}",
        "0011223344556677",
        "{\"begin_status\":\"attempts_exhausted\",\"callback_exception\":false,\"finish_status\":\"unused\",\"material\":\"none\",\"replay\":false,\"token\":\"none\"}",
        "{\"callback_exception\":false,\"key_id\":\"none\",\"status\":\"unused\"}",
        INT32_C(0),
        "ok",
        "{\"status\":\"rejected\",\"reason\":\"attempts_exhausted\"}",
        "[\"begin_attempt\",\"observe:verification_completed\"]",
        UINT32_C(0),
        "[\"MATERIAL_SENTINEL\"]"
    },
    {
        "lifecycle_binding_mismatch",
        "verify",
        "{\"answer\":\"YQ\",\"challenge_id\":\"Y2hhbGxlbmdlLTEyMzQ1Ng\",\"nonce\":\"bm9uY2UtMTIzNDU2Nzg5MA\"}",
        "0011223344556677",
        "{\"begin_status\":\"binding_mismatch\",\"callback_exception\":false,\"finish_status\":\"unused\",\"material\":\"none\",\"replay\":false,\"token\":\"none\"}",
        "{\"callback_exception\":false,\"key_id\":\"none\",\"status\":\"unused\"}",
        INT32_C(0),
        "ok",
        "{\"status\":\"rejected\",\"reason\":\"binding_mismatch\"}",
        "[\"begin_attempt\",\"observe:verification_completed\"]",
        UINT32_C(0),
        "[\"BINDING_SENTINEL\"]"
    },
    {
        "lifecycle_expired",
        "verify",
        "{\"answer\":\"YQ\",\"challenge_id\":\"Y2hhbGxlbmdlLTEyMzQ1Ng\",\"nonce\":\"bm9uY2UtMTIzNDU2Nzg5MA\"}",
        "0011223344556677",
        "{\"begin_status\":\"expired\",\"callback_exception\":false,\"finish_status\":\"unused\",\"material\":\"none\",\"replay\":false,\"token\":\"none\"}",
        "{\"callback_exception\":false,\"key_id\":\"none\",\"status\":\"unused\"}",
        INT32_C(0),
        "ok",
        "{\"status\":\"rejected\",\"reason\":\"expired\"}",
        "[\"begin_attempt\",\"observe:verification_completed\"]",
        UINT32_C(0),
        "[\"MATERIAL_SENTINEL\"]"
    },
    {
        "lifecycle_nonce_mismatch",
        "verify",
        "{\"answer\":\"YQ\",\"challenge_id\":\"Y2hhbGxlbmdlLTEyMzQ1Ng\",\"nonce\":\"bm9uY2UtMTIzNDU2Nzg5MA\"}",
        "0011223344556677",
        "{\"begin_status\":\"nonce_mismatch\",\"callback_exception\":false,\"finish_status\":\"unused\",\"material\":\"none\",\"replay\":false,\"token\":\"none\"}",
        "{\"callback_exception\":false,\"key_id\":\"none\",\"status\":\"unused\"}",
        INT32_C(0),
        "ok",
        "{\"status\":\"rejected\",\"reason\":\"nonce_mismatch\"}",
        "[\"begin_attempt\",\"observe:verification_completed\"]",
        UINT32_C(0),
        "[\"NONCE_SENTINEL\"]"
    },
    {
        "lifecycle_not_found",
        "verify",
        "{\"answer\":\"YQ\",\"challenge_id\":\"Y2hhbGxlbmdlLTEyMzQ1Ng\",\"nonce\":\"bm9uY2UtMTIzNDU2Nzg5MA\"}",
        "0011223344556677",
        "{\"begin_status\":\"not_found\",\"callback_exception\":false,\"finish_status\":\"unused\",\"material\":\"none\",\"replay\":false,\"token\":\"none\"}",
        "{\"callback_exception\":false,\"key_id\":\"none\",\"status\":\"unused\"}",
        INT32_C(0),
        "ok",
        "{\"status\":\"rejected\",\"reason\":\"not_found\"}",
        "[\"begin_attempt\",\"observe:verification_completed\"]",
        UINT32_C(0),
        "[\"MATERIAL_SENTINEL\"]"
    },
    {
        "observer_allowlist",
        "observe",
        "{\"answer\":\"YQ\",\"challenge_id\":\"Y2hhbGxlbmdlLTEyMzQ1Ng\",\"nonce\":\"bm9uY2UtMTIzNDU2Nzg5MA\"}",
        "0011223344556677",
        "{\"begin_status\":\"ok\",\"callback_exception\":false,\"finish_status\":\"ok\",\"material\":\"primary\",\"replay\":false,\"token\":\"default\"}",
        "{\"callback_exception\":false,\"key_id\":\"old\",\"status\":\"ok\"}",
        INT32_C(0),
        "ok",
        "{\"status\":\"accepted\"}",
        "[\"begin_attempt\",\"release:token\",\"release:material\",\"key_by_id:old\",\"release:key\",\"finish_attempt:accepted\",\"observe:verification_completed\"]",
        UINT32_C(3),
        "[\"PRIVATE_ANSWER_SENTINEL\",\"KEY_SENTINEL\",\"TOKEN_SENTINEL\"]"
    },
    {
        "replay_after_accept",
        "verify",
        "{\"answer\":\"YQ\",\"challenge_id\":\"Y2hhbGxlbmdlLTEyMzQ1Ng\",\"nonce\":\"bm9uY2UtMTIzNDU2Nzg5MA\"}",
        "0011223344556677",
        "{\"begin_status\":\"already_consumed\",\"callback_exception\":false,\"finish_status\":\"unused\",\"material\":\"none\",\"replay\":true,\"token\":\"none\"}",
        "{\"callback_exception\":false,\"key_id\":\"none\",\"status\":\"unused\"}",
        INT32_C(0),
        "ok",
        "{\"status\":\"rejected\",\"reason\":\"already_consumed\"}",
        "[\"begin_attempt\",\"observe:verification_completed\"]",
        UINT32_C(0),
        "[\"REPLAY_MATERIAL_SENTINEL\"]"
    },
};

#define AG_BINDING_FIXTURE_CASE_COUNT \
    (sizeof(AG_BINDING_FIXTURE_CASES) / sizeof(AG_BINDING_FIXTURE_CASES[0]))

#endif /* COGGATE_GENERATED_FIXTURES_H */
